# House Prices Modeling — pw1
Sections:
1. Setup & imports
2. Load dataset
3. Quick EDA
4. Feature selection
5. Preprocessing
6. Model training
7. Evaluation
8. Conclusion

In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_log_error

def compute_rmsle(y_test: np.ndarray, y_pred: np.ndarray, precision: int = 3) -> float:
    """RMSLE as required by assignment"""
    rmsle = np.sqrt(mean_squared_log_error(y_test, y_pred))
    return round(rmsle, precision)

In [6]:

df = pd.read_csv("/Users/zainulislam/train.csv")
print("shape:", df.shape)


df.head(20)

shape: (1460, 81)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000
10,11,20,RL,70.0,11200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,129500
11,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,New,Partial,345000
12,13,20,RL,NaN,12968,Pave,NaN,IR2,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,144000
13,14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,New,Partial,279500
14,15,20,RL,NaN,10920,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2008,WD,Normal,157000
15,16,45,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,7,2007,WD,Normal,132000
16,17,20,RL,NaN,11241,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,700,3,2010,WD,Normal,149000
17,18,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,Shed,500,10,2006,WD,Normal,90000
18,19,20,RL,66.0,13695,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,159000
19,20,20,RL,70.0,7560,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2009,COD,Abnorml,139000

In [7]:

df = pd.read_csv("/Users/zainulislam/train.csv")
print("shape:", df.shape)


df.head(20)

shape: (1460, 81)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000
10,11,20,RL,70.0,11200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,129500
11,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,New,Partial,345000
12,13,20,RL,NaN,12968,Pave,NaN,IR2,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,144000
13,14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,New,Partial,279500
14,15,20,RL,NaN,10920,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2008,WD,Normal,157000
15,16,45,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,7,2007,WD,Normal,132000
16,17,20,RL,NaN,11241,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,700,3,2010,WD,Normal,149000
17,18,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,Shed,500,10,2006,WD,Normal,90000
18,19,20,RL,66.0,13695,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,159000
19,20,20,RL,70.0,7560,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2009,COD,Abnorml,139000

## Feature selection
I will use at least 2 continuous and 2 categorical features. I pick:
- Continuous: `MSSubClass`, `LotFrontage`
- Categorical: `MSZoning`, `Street`

(Explain any choice here — e.g., completeness, low missingness, potential predictive power.)

In [8]:
cont_features = ["MSSubClass", "LotFrontage"]
cat_features = ["MSZoning", "Street"]
features = cont_features + cat_features

df[features].head(20)

    MSSubClass  LotFrontage MSZoning Street
0           60         65.0       RL   Pave
1           20         80.0       RL   Pave
2           60         68.0       RL   Pave
3           70         60.0       RL   Pave
4           60         84.0       RL   Pave
5           50         85.0       RL   Pave
6           20         75.0       RL   Pave
7           60          NaN       RL   Pave
8           50         51.0       RM   Pave
9          190         50.0       RL   Pave
10          20         70.0       RL   Pave
11          60         85.0       RL   Pave
12          20          NaN       RL   Pave
13          20         91.0       RL   Pave
14          20          NaN       RL   Pave
15          45         51.0       RM   Pave
16          20          NaN       RL   Pave
17          90         72.0       RL   Pave
18          20         66.0       RL   Pave
19          20         70.0       RL   Pave

In [9]:

target = "SalePrice"


cont_features = ["MSSubClass", "LotFrontage"]   
cat_features  = ["MSZoning", "Street"]         
features = cont_features + cat_features

In [10]:
X = df[features].copy()
y = df[target].copy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

print("X_train:", X_train.shape, "X_test:", X_test.shape)

X_train: (1168, 4) X_test: (292, 4)

In [23]:
from sklearn.preprocessing import OneHotEncoder


num_imputer = SimpleImputer(strategy="median")
scaler = StandardScaler()

X_train_num = num_imputer.fit_transform(X_train[cont_features])
X_train_num_scaled = scaler.fit_transform(X_train_num)

X_test_num = num_imputer.transform(X_test[cont_features])
X_test_num_scaled = scaler.transform(X_test_num)


cat_imputer = SimpleImputer(strategy="constant", fill_value="Missing")
X_train_cat = cat_imputer.fit_transform(X_train[cat_features])
X_test_cat  = cat_imputer.transform(X_test[cat_features])

import sklearn

if int(sklearn.__version__.split(".")[1]) >= 2: 
    ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
else:
    ohe = OneHotEncoder(handle_unknown="ignore", sparse=False)

X_train_cat_ohe = ohe.fit_transform(X_train_cat)
X_test_cat_ohe  = ohe.transform(X_test_cat)


cat_feature_names = ohe.get_feature_names_out(cat_features)


X_train_cat_df = pd.DataFrame(X_train_cat_ohe, columns=cat_feature_names, index=X_train.index)
X_test_cat_df  = pd.DataFrame(X_test_cat_ohe,  columns=cat_feature_names, index=X_test.index)


X_train_prep = pd.DataFrame(X_train_num_scaled, columns=cont_features, index=X_train.index).join(X_train_cat_df)
X_test_prep  = pd.DataFrame(X_test_num_scaled, columns=cont_features, index=X_test.index).join(X_test_cat_df)

print("Prepared X_train:", X_train_prep.shape)
print("Prepared X_test :", X_test_prep.shape)

Prepared X_train: (1168, 9)
Prepared X_test : (292, 9)

In [24]:

y_train_log = np.log1p(y_train)

model = RandomForestRegressor(n_estimators=200, random_state=42, n_jobs=-1)
model.fit(X_train_prep, y_train_log)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [25]:
y_pred_log = model.predict(X_test_prep)
y_pred = np.expm1(y_pred_log)

rmsle = compute_rmsle(y_test.values, y_pred)
print("RMSLE on test set:", rmsle)

RMSLE on test set: 0.305

In [27]:
compare_df = pd.DataFrame({
    "y_true": y_test,
    "y_pred": y_pred,
}).reset_index(drop=True).sample(min(10, len(y_test)), random_state=1)

compare_df


importances = pd.Series(model.feature_importances_, index=X_train_prep.columns).sort_values(ascending=False)
importances.head(10)

LotFrontage         0.502261
MSSubClass          0.329587
MSZoning_RM         0.121519
MSZoning_RL         0.013871
MSZoning_C (all)    0.012631
MSZoning_FV         0.010207
MSZoning_RH         0.006756
Street_Grvl         0.001650
Street_Pave         0.001517
dtype: float64